server:
  port: 9999
spring:
  application:
    name: ragflow_java
  # 配置devtools
  devtools:
    restart:
      enabled: true  # 启用热部署
      additional-paths: src/main/java  # 设置重启的目录
      exclude: static/**,public/**  # 静态资源不重启
    livereload:
      enabled: true  # 启用livereload
  datasource:
    url: jdbc:mysql://localhost:3306/ragflow_demo?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root  # 修改为正确的密码
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  # 设置jackson日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# MyBatis配置
mybatis:
  check-config-location: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xiao.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

# 加密配置
security:
  encrypt:
    salt: RagFlow2024SecretSalt # 加密盐值

# Knife4j配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: default
      paths-to-match: /**
      packages-to-scan: com.xiao.controller
  # 是否启用swagger，生产环境建议关闭
  enable: true
  # 是否启用接口数据对比
  enable-diff: true

# Knife4j增强配置
knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-swagger-models: true
    enable-document-manage: true
    swagger-model-name: 实体类列表
    enable-version: true
    enable-footer: false
    enable-footer-custom: true
    footer-custom-content: RAGFlow API文档

# RAGFlow配置
ragflow:
  api:
    key: ragflow-IwMmE4YTJlZmZlODExZWZhMzhjMDI0Mm
    base-url: http://127.0.0.1
    version: v1